# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

app_store_connect_api_key(
  key_id: "Z9L46VG577",
  issuer_id: "89f08ee0-08b1-440f-a90a-f2bdbb4b32e0",
  key_filepath: "fastlane/AuthKey_Z9L46VG577.p8",
  in_house: false
)

platform :ios do

  desc "Distribute to both internal and external testers"
  lane :beta do
    build_app(
      scheme: "CICD",
      export_method: "app-store"
    )

    # Distribute to internal testers
    upload_to_testflight(
      distribute_external: false,
      groups: ["Internal"]
    )

    # Attempt to distribute to external testers
    begin
      upload_to_testflight(
        distribute_external: true,
        groups: ["External"],
        beta_app_description: "This is a beta build for external testers.",
        beta_app_feedback_email: "shames.asghar@hypernymbiz.com"
      )

      submit_for_review(
        automatic_release: true
      )
    rescue => error
      UI.important("⚠️ Could not submit for external review: #{error.message}")
      UI.important("🔁 Likely because another build is still in review. Try again later.")
    end
  end
end
